title: "Augusto"
baseURL: "https://v3natio.github.io/"
theme:
  - "PaperModX"
locale: "en-us"

params:
  env: "production"
  title: "Augusto"
  description: "Data Science Intern at ING. I post some educational content about math and CS on my website. I also describe the projects I've worked on." # shown on web preview
  keywords: [Augusto Zerpa, venatio, uc3m, computer science, cs, python, py, machine learning, ml, artificial intelligence, ai, linux, unix, arch linux, arch, mathematics, math, economics, econometrics, econ, blog, portfolio]
  author: "venatio"
  images: ["/img/logo_out.png"] # web preview
  defaultTheme: "auto"
  DateFormat: "January 2, 2006"
  LastModFormat: "January 2, 2006"
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowSocialIcons: true
  ShowToc: true
  TocOpen: true
  TocSide: "left"
  math: true
  comments: true
  ShowAllPagesInArchive: true

  mainSections:
    - posts
    - projects

  assets:
    disableHLJS: true # use Hugo's chroma

  logo:
    icon: "/img/logo_out.png" # top left corner
    iconHeight: 35

  profileMode:
    enabled: true
    subtitle: "Data Science Intern at <a href=\"https://ing.com/\">ING</a>, and Econometrics BSc student at <a href=\"https://uc3m.es/\">UC3M</a>. <br> <a href=\"/about\">More about me</a>."
    imageUrl: "/img/me.jpg" # center
    imageWidth: 150
    imageHeight: 150
    buttons:
      - name: Posts
        url: /posts
      - name: Tags
        url: /tags
      - name: Archives
        url: /archives

  socialIcons:
    - name: cv
      url: "https://www.linkedin.com/in/augustoz/"
    - name: github
      url: "https://github.com/v3natio"
    - name: linkedin
      url: "https://www.linkedin.com/in/augustoz/"
    - name: rss
      url: "/index.xml"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNos: true

outputs:
  home: ["HTML", "RSS", "JSON"]
  section: ["HTML"]

menu:
  main:
    - identifier: about
      name: "About"
      url: "/about/"
      weight: 1
    - identifier: posts
      name: "Posts"
      url: "/posts/"
      weight: 2
    - identifier: projects
      name: "Projects"
      url: "/projects/"
      weight: 3
    - identifier: search
      name: "Search"
      url: "/search/"
      weight: 4

enableRobotsTXT: true
enableGitInfo: true # for lastmod date

sitemap:
  changefreq: weekly

minify:
  minifyOutput: true

permalinks:
  posts: "/posts/:slug/"
