title: "venatio"
baseURL: "https://v3natio.github.io/"
theme: "PaperMod"
languageCode: "en-us"

params:
  env: "production"
  title: "venatio"
  description: "Econometrics student at UC3M. Welcome to my website!" # shown on web preview
  keywords: [Augusto Zerpa, Blog, Portfolio, Economics, Mathematics, CS, Linux, Arch Linux]
  author: "venatio"
  images: ["/img/logo_out.png"] # shown on web preview
  defaultTheme: "auto"
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowSocialIcons: true
  TocOpen: true
  TocSide: "left"
  math: true
  comments: true
  ShowAllPagesInArchive: true

  mainSections:
    - posts
    - projects

  assets:
    disableHLJS: true # use Hugo's chroma

  logo:
    icon: "/img/logo_out.png"
    iconHeight: 35

  profileMode:
    enabled: true
    subtitle: "Econometrics student with a knack for quantitative finance. <a href=\"/about\">More about me</a>."
    imageUrl: "/img/logo_out.png"
    imageWidth: 150
    imageHeight: 150
    buttons:
      - name: Posts
        url: /posts
      - name: Tags
        url: /tags
      - name: Archives
        url: /archives

  socialIcons:
    - name: github
      url: "https://github.com/v3natio"
    - name: linkedin
      url: "https://www.linkedin.com/in/augustoz/"
    - name: rss
      url: "index.xml"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNos: false

outputs:
  home: ["HTML", "RSS", "JSON"]
  section: ["HTML"]

menu:
  main:
    - identifier: about
      name: "About"
      url: "/about/"
      weight: 1
    - identifier: projects
      name: "Projects"
      url: "/projects/"
      weight: 2
    - identifier: search
      name: "Search"
      url: "/search/"
      weight: 3

enableRobotsTXT: true
sitemap:
  changefreq: weekly
