baseURL = "https://v3natio.github.io/"
languageCode = "en-us"
title = "v3natio"
theme = "PaperMod"

[params]
author = "v3natio"
ShowSocialIcons = true

[[params.socialIcons]]
name = "github"
url = "https://github.com/v3natio"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/augustoz/"

[[params.socialIcons]]
name = "rss"
url = "index.xml"

[outputs]
home = ["HTML", "RSS", "JSON"]

[[menu.main]]
identifier = "resume"
name = "CV"
url = "/resume/"
weight = 10

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 20
